name: OPA Policy Check

on:
  push:
    branches:
      - main

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Conftest (Fixed Version)
        uses: princespaghetti/setup-conftest@v1
        with:
          version: 0.45.0

      - name: Verify Installation
        run: conftest --version

      - name: Debug Files
        run: |
          echo "FILES:"
          ls -R
          echo "POLICY CONTENT:"
          cat policy/policy.rego

      - name: Run OPA Policy Check
        run: |
          conftest test config.json --policy policy/