name: OPA Policy Check

on:
  push:
    branches:
      - main

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Conftest
        uses: princespaghetti/setup-conftest@v1

      - name: Verify Installation
        run: conftest --version

      - name: Run OPA Policy Check
        run: |
          conftest test config.json --policy policy/